@BASE_URL = http://localhost:3000/api
@TOKEN = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NGJmN2MwMzAwYWYyZWRlYzFmN2I3NTkiLCJlbWFpbCI6ImxpbmtzaG9ydGVuZXJwcm9qZWN0QGdtYWlsLmNvbSIsInVzZXJuYW1lIjoibGlua3Nob3J0ZW5lcnByb2plY3RAZ21haWwuY29tIiwiaXNBZG1pbiI6ZmFsc2UsImxpbmtzIjpbXSwiaWF0IjoxNjkwMjcxOTIzLCJleHAiOjE2OTAzNTgzMjN9.PHYVnxm6w64HeBI_k7AGzA4K02JdTuQfTCoU9Kt0SVo


GET {{BASE_URL}}

###
GET {{BASE_URL}}/users

###
GET {{BASE_URL}}/users/64b7bcabf7d75f2fb0b330fa

###
POST {{BASE_URL}}/users/saveUser
Content-Type: application/json

{
    "email" : "linkshortenerproject@gmail.com",
    "username" : "saner",
    "password" : "123456"
}

###
PATCH  {{BASE_URL}}/users/64b7bcabf7d75f2fb0b330fa
Content-Type: application/json

{
    "password" : "159753",
    "username" : "saners"
}

###
DELETE  {{BASE_URL}}/users/64b7bcabf7d75f2fb0b330fa
Content-Type: application/json


###
GET  {{BASE_URL}}/users/deleteAllUsers
Content-Type: application/json
Authorization: {{TOKEN}}

###
POST {{BASE_URL}}/users/signin
Content-Type: application/json

{
    "email" : "dogukan@hotmail.com",
    "password" : "123456"
}

###
POST {{BASE_URL}}/users/signin
Content-Type: application/json

{
    "email" : "linkshortenerproject@gmail.com",
    "password" : "123456"
}

###
PATCH {{BASE_URL}}/users/updateUser/64be5cad7faca271f8093551
Content-Type: application/json
Authorization: {{TOKEN}}

{
    "email" : "saners@hotmail.com",
    "password": "123456"
}


###
GET {{BASE_URL}}/users/me
Content-Type: application/json
Authorization: {{TOKEN}}

{
    "email" : "dogukan@gmail.com",
    "password" : "dodo123"
}


###
PATCH  {{BASE_URL}}/users/me
Content-Type: application/json
Authorization: {{TOKEN}}

{
    "password" : "159753",
    "username" : "saneratis"
}


###
GET  {{BASE_URL}}/users/getAllUsers
Content-Type: application/json
Authorization: {{TOKEN}}

{
    "password" : "merhaba",
    "username" : "dogukan"
}

###
POST  {{BASE_URL}}/links/add/
Content-Type: application/json
Authorization: {{TOKEN}}

{
    "original_link" : "https://universetheapp.com"
}


###
DELETE  {{BASE_URL}}/links/deleteMyLink/64ba37fbfe06e8cec30545db
Content-Type: application/json
Authorization: {{TOKEN}}


###
DELETE  {{BASE_URL}}/links/deleteAll
Content-Type: application/json
Authorization: {{TOKEN}}


###
DELETE  {{BASE_URL}}/links/delete/64ba37e5fe06e8cec30545d8
Content-Type: application/json
Authorization: {{TOKEN}}

###
GET  {{BASE_URL}}/links/redirect/FSBNWQ
Content-Type: application/json


###
GET http://localhost:3000/verifyEmail?id=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0YmU4YTI3YTJlOTliYTJlZDE5MzE2ZSIsImVtYWlsIjoibGlua3Nob3J0ZW5lcnByb2plY3RAZ21haWwuY29tIiwiaWF0IjoxNjkwMjA4ODA3LCJleHAiOjE2OTAyOTUyMDd9.vRWC-Ac-pMm6QBdMjDJX4ds1RMS_5YqWErCrsvHJA0o



###
POST  {{BASE_URL}}/users/forgotPassword
Content-Type: application/json

{
    "email": "linkshortenerproject@gmail.com"
}