@BASE_URL = http://localhost:3000/api
@TOKEN = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NGJhMzdhMGZlMDZlOGNlYzMwNTQ1ZDIiLCJlbWFpbCI6ImRvZ3VrYW5AaG90bWFpbC5jb20iLCJ1c2VybmFtZSI6ImRvZ3VrYW5AaG90bWFpbC5jb20iLCJpc0FkbWluIjp0cnVlLCJsaW5rcyI6W10sImlhdCI6MTY4OTkyNTg0MCwiZXhwIjoxNjkwMDEyMjQwfQ.cWr25koAMwGr05EO0rh3XGT5h2KPZ1aOS7-bxYuKrDY


GET {{BASE_URL}}

###
GET {{BASE_URL}}/users

###
GET {{BASE_URL}}/users/64b7bcabf7d75f2fb0b330fa

###
POST {{BASE_URL}}/users/saveUser
Content-Type: application/json

{
    "email" : "saner@hotmail.com",
    "username" : "saner",
    "password" : "123456"
}

###
PATCH  {{BASE_URL}}/users/64b7bcabf7d75f2fb0b330fa
Content-Type: application/json

{
    "password" : "159753",
    "username" : "saners"
}

###
DELETE  {{BASE_URL}}/users/64b7bcabf7d75f2fb0b330fa
Content-Type: application/json


###
GET  {{BASE_URL}}/users/deleteAllUsers
Content-Type: application/json
Authorization: {{TOKEN}}

###
POST {{BASE_URL}}/users/signin
Content-Type: application/json

{
    "email" : "dogukan@hotmail.com",
    "password" : "123456"
}

###
POST {{BASE_URL}}/users/signin
Content-Type: application/json

{
    "email" : "saner@hotmail.com",
    "password" : "123456"
}


###
GET {{BASE_URL}}/users/me
Content-Type: application/json
Authorization: {{TOKEN}}

{
    "email" : "dogukan@gmail.com",
    "password" : "dodo123"
}


###
PATCH  {{BASE_URL}}/users/me
Content-Type: application/json
Authorization: {{TOKEN}}

{
    "password" : "159753",
    "username" : "saneratis"
}


###
GET  {{BASE_URL}}/users/getAllUsers
Content-Type: application/json
Authorization: {{TOKEN}}

{
    "password" : "merhaba",
    "username" : "dogukan"
}

###
POST  {{BASE_URL}}/links/add/
Content-Type: application/json
Authorization: {{TOKEN}}

{
    "original_link" : "universetheapp.com",
    "short_link" : "shrtlnk.com/abc",
    "belongs_to" : "64ba37a0fe06e8cec30545d2"
}


###
DELETE  {{BASE_URL}}/links/deleteMyLink/64ba37fbfe06e8cec30545db
Content-Type: application/json
Authorization: {{TOKEN}}

###
DELETE  {{BASE_URL}}/links/delete/64ba37e5fe06e8cec30545d8
Content-Type: application/json
Authorization: {{TOKEN}}